#    QPane - High-performance PySide6 image viewer
#    Copyright (C) 2025  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Expose QPane's supported host-neutral execution SDK."""

from ..execution import (
    BackendSubmission,
    CancellationToken,
    CompletionDispatcher,
    DefaultExecutionPolicy,
    DelayHandle,
    DelayScheduler,
    DiagnosticsSubscription,
    ExecutionBackend,
    ExecutionBackendCapabilities,
    ExecutionDiagnosticsProvider,
    ExecutionFailurePhase,
    ExecutionHandle,
    ExecutionJob,
    ExecutionLeaseRelease,
    ExecutionOutcome,
    ExecutionProgressReporter,
    ExecutionRejected,
    ExecutionRejectionReason,
    ExecutionRequest,
    ExecutionRequirements,
    ExecutionResource,
    ExecutionRuntime,
    ExecutionScope,
    ExecutionSnapshot,
    ExecutionState,
    ExecutionTagValue,
    ExecutionTaskContext,
    ExecutionTimings,
    ExecutionUrgency,
    InlineDispatcher,
    QtDelayScheduler,
    QtOwnerDispatcher,
    RetryCategorySnapshot,
    RetryContext,
    RetryController,
    RetryPolicy,
    RetrySchedulingError,
    RetrySnapshot,
    create_default_execution_runtime,
    create_native_execution_runtime,
    execution_detail_records,
    execution_summary_records,
    retry_detail_records,
    retry_summary_records,
)

__all__ = (
    "BackendSubmission",
    "CancellationToken",
    "CompletionDispatcher",
    "DefaultExecutionPolicy",
    "DelayHandle",
    "DelayScheduler",
    "DiagnosticsSubscription",
    "ExecutionBackend",
    "ExecutionBackendCapabilities",
    "ExecutionDiagnosticsProvider",
    "ExecutionFailurePhase",
    "ExecutionHandle",
    "ExecutionJob",
    "ExecutionLeaseRelease",
    "ExecutionOutcome",
    "ExecutionProgressReporter",
    "ExecutionRejected",
    "ExecutionRejectionReason",
    "ExecutionRequest",
    "ExecutionRequirements",
    "ExecutionResource",
    "ExecutionRuntime",
    "ExecutionScope",
    "ExecutionSnapshot",
    "ExecutionState",
    "ExecutionTagValue",
    "ExecutionTaskContext",
    "ExecutionTimings",
    "ExecutionUrgency",
    "InlineDispatcher",
    "QtDelayScheduler",
    "QtOwnerDispatcher",
    "RetryCategorySnapshot",
    "RetryContext",
    "RetryController",
    "RetryPolicy",
    "RetrySchedulingError",
    "RetrySnapshot",
    "create_default_execution_runtime",
    "create_native_execution_runtime",
    "execution_detail_records",
    "execution_summary_records",
    "retry_detail_records",
    "retry_summary_records",
)
