#    QPane - High-performance PySide6 image viewer
#    Copyright (C) 2025  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Expose QPane's focused viewer and declarative raster/vector rendering SDK."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "BackendSubmission",
    "BilinearLayerTransform",
    "BlendMode",
    "CacheMode",
    "CancellationToken",
    "ClipCoordinateSpace",
    "ComparisonDividerState",
    "ComparisonOrientation",
    "ComparisonState",
    "CompletionDispatcher",
    "Config",
    "CursorInteractionPort",
    "CursorTool",
    "DefaultExecutionPolicy",
    "DelayHandle",
    "DelayScheduler",
    "DiagnosticRecord",
    "Diagnostics",
    "DiagnosticsSnapshot",
    "DiagnosticsSubscription",
    "ExecutionBackend",
    "ExecutionBackendCapabilities",
    "ExecutionDiagnosticsProvider",
    "ExecutionFailurePhase",
    "ExecutionHandle",
    "ExecutionJob",
    "ExecutionLeaseRelease",
    "ExecutionOutcome",
    "ExecutionProgressReporter",
    "ExecutionRejected",
    "ExecutionRejectionReason",
    "ExecutionRequest",
    "ExecutionRequirements",
    "ExecutionResource",
    "ExecutionRuntime",
    "ExecutionScope",
    "ExecutionSnapshot",
    "ExecutionState",
    "ExecutionTagValue",
    "ExecutionTaskContext",
    "ExecutionTimings",
    "ExecutionUrgency",
    "HybridCombineMode",
    "HybridDocument",
    "HybridPresentationStyle",
    "HybridRasterPrimitive",
    "HybridRasterSampler",
    "HybridSource",
    "HybridVectorPrimitive",
    "IncompleteRowAlignment",
    "InlineDispatcher",
    "InspectionRegion",
    "InspectionStateStore",
    "InspectionTarget",
    "InspectionUpdate",
    "InspectionViewState",
    "InspectionZoomMode",
    "LayerClip",
    "LayerLocalPoint",
    "LayerMapping",
    "LayerPresentationEffect",
    "LayerPresentationEffectKind",
    "LayerPresentationStyle",
    "LayerSourcePoint",
    "LayerTransform",
    "LinkedGroup",
    "NavigationInteractionPort",
    "OutboundDragPayload",
    "OutboundMimeItem",
    "PanZoomTool",
    "PanelHitTest",
    "PanelPoint",
    "PiecewiseLayerTransform",
    "PointerDeviceKind",
    "PointerInputController",
    "PointerInputPort",
    "PointerPhase",
    "PointerSample",
    "ProjectedViewport",
    "ProjectiveLayerTransform",
    "QPane",
    "QtDelayScheduler",
    "QtOwnerDispatcher",
    "RasterBounds",
    "RasterHitTestProvider",
    "RasterProductPolicy",
    "RasterSource",
    "RasterSourcePatch",
    "RasterSourceProvider",
    "RenderLayer",
    "RenderScene",
    "ResponsiveGridLayout",
    "ResponsiveGridPolicy",
    "ResponsiveGridSnapshot",
    "ResponsiveGridTopology",
    "RetryCategorySnapshot",
    "RetryContext",
    "RetryController",
    "RetryPolicy",
    "RetrySchedulingError",
    "RetrySnapshot",
    "SceneCoordinateSystem",
    "ScenePoint",
    "SceneSnapshotOverlayLayer",
    "SceneSnapshotOverlayState",
    "SparseRasterSourceProvider",
    "TileSizeSetting",
    "ToolInputProfile",
    "ToolManager",
    "ToolManagerSignals",
    "TouchGestureArena",
    "TouchGestureKind",
    "TouchNavigationPort",
    "TouchNavigationSession",
    "TriangularLayerMappingPatch",
    "VectorDocument",
    "VectorFillRule",
    "VectorObject",
    "VectorObjectKind",
    "VectorParagraphStyle",
    "VectorPathCommand",
    "VectorPathCommandKind",
    "VectorShapeKind",
    "VectorSource",
    "VectorStrokeCap",
    "VectorStrokeJoin",
    "VectorStyle",
    "VectorTextAlignment",
    "VectorTextContent",
    "VectorTextDirection",
    "VectorTextSpan",
    "VectorTextStyle",
    "ViewerCatalog",
    "ViewerCatalogEntry",
    "ViewerPlaceholderState",
    "ViewerPrefetchSnapshot",
    "ViewerTool",
    "ViewerToolSignals",
    "ViewportZoomMode",
    "ZoomMode",
    "__version__",
    "capture_inspection",
    "create_default_execution_runtime",
    "create_native_execution_runtime",
    "execution_detail_records",
    "execution_summary_records",
    "project_inspection",
    "retry_detail_records",
    "retry_summary_records",
]

_LAZY_SYMBOLS: dict[str, tuple[str, str]] = {
    "BackendSubmission": ("qpane.sdk.execution", "BackendSubmission"),
    "QPane": ("qpane.viewer", "QPane"),
    "Config": ("qpane.core.config", "Config"),
    "TileSizeSetting": ("qpane.core.config", "TileSizeSetting"),
    "CacheMode": ("qpane.types", "CacheMode"),
    "ClipCoordinateSpace": ("qpane.scene.model", "ClipCoordinateSpace"),
    "ComparisonDividerState": ("qpane.types", "ComparisonDividerState"),
    "ComparisonOrientation": ("qpane.types", "ComparisonOrientation"),
    "ComparisonState": ("qpane.types", "ComparisonState"),
    "ZoomMode": ("qpane.types", "ZoomMode"),
    "ViewportZoomMode": ("qpane.rendering.viewport", "ViewportZoomMode"),
    "BlendMode": ("qpane.scene.model", "BlendMode"),
    "LayerClip": ("qpane.scene.model", "LayerClip"),
    "LayerPresentationEffect": (
        "qpane.scene.presentation_effects",
        "LayerPresentationEffect",
    ),
    "LayerPresentationEffectKind": (
        "qpane.scene.presentation_effects",
        "LayerPresentationEffectKind",
    ),
    "LayerPresentationStyle": (
        "qpane.scene.presentation_effects",
        "LayerPresentationStyle",
    ),
    "LayerTransform": ("qpane.scene.affine", "LayerTransform"),
    "LayerMapping": ("qpane.scene.mapping", "LayerMapping"),
    "BilinearLayerTransform": (
        "qpane.scene.bilinear",
        "BilinearLayerTransform",
    ),
    "PiecewiseLayerTransform": (
        "qpane.scene.piecewise",
        "PiecewiseLayerTransform",
    ),
    "ProjectiveLayerTransform": (
        "qpane.scene.projective",
        "ProjectiveLayerTransform",
    ),
    "TriangularLayerMappingPatch": (
        "qpane.scene.piecewise",
        "TriangularLayerMappingPatch",
    ),
    "LayerLocalPoint": ("qpane.rendering.scene_coordinates", "LayerLocalPoint"),
    "LayerSourcePoint": ("qpane.rendering.scene_coordinates", "LayerSourcePoint"),
    "PanelHitTest": ("qpane.rendering.coordinates", "PanelHitTest"),
    "PanelPoint": ("qpane.rendering.scene_coordinates", "PanelPoint"),
    "SceneCoordinateSystem": (
        "qpane.rendering.scene_coordinates",
        "SceneCoordinateSystem",
    ),
    "ScenePoint": ("qpane.rendering.scene_coordinates", "ScenePoint"),
    "PointerDeviceKind": ("qpane.interaction", "PointerDeviceKind"),
    "PointerInputController": ("qpane.interaction", "PointerInputController"),
    "PointerInputPort": ("qpane.interaction", "PointerInputPort"),
    "PointerPhase": ("qpane.interaction", "PointerPhase"),
    "PointerSample": ("qpane.interaction", "PointerSample"),
    "CursorInteractionPort": ("qpane.interaction", "CursorInteractionPort"),
    "CursorTool": ("qpane.interaction", "CursorTool"),
    "CancellationToken": ("qpane.sdk.execution", "CancellationToken"),
    "CompletionDispatcher": ("qpane.sdk.execution", "CompletionDispatcher"),
    "DefaultExecutionPolicy": (
        "qpane.sdk.execution",
        "DefaultExecutionPolicy",
    ),
    "DelayHandle": ("qpane.sdk.execution", "DelayHandle"),
    "DelayScheduler": ("qpane.sdk.execution", "DelayScheduler"),
    "DiagnosticRecord": ("qpane.types", "DiagnosticRecord"),
    "Diagnostics": ("qpane.core", "Diagnostics"),
    "DiagnosticsSnapshot": ("qpane.core", "DiagnosticsSnapshot"),
    "DiagnosticsSubscription": (
        "qpane.sdk.execution",
        "DiagnosticsSubscription",
    ),
    "ExecutionBackend": ("qpane.sdk.execution", "ExecutionBackend"),
    "ExecutionBackendCapabilities": (
        "qpane.sdk.execution",
        "ExecutionBackendCapabilities",
    ),
    "ExecutionDiagnosticsProvider": (
        "qpane.sdk.execution",
        "ExecutionDiagnosticsProvider",
    ),
    "ExecutionFailurePhase": (
        "qpane.sdk.execution",
        "ExecutionFailurePhase",
    ),
    "ExecutionHandle": ("qpane.sdk.execution", "ExecutionHandle"),
    "ExecutionJob": ("qpane.sdk.execution", "ExecutionJob"),
    "ExecutionLeaseRelease": (
        "qpane.sdk.execution",
        "ExecutionLeaseRelease",
    ),
    "ExecutionOutcome": ("qpane.sdk.execution", "ExecutionOutcome"),
    "ExecutionProgressReporter": (
        "qpane.sdk.execution",
        "ExecutionProgressReporter",
    ),
    "ExecutionRejected": ("qpane.sdk.execution", "ExecutionRejected"),
    "ExecutionRejectionReason": (
        "qpane.sdk.execution",
        "ExecutionRejectionReason",
    ),
    "ExecutionRequest": ("qpane.sdk.execution", "ExecutionRequest"),
    "ExecutionRequirements": (
        "qpane.sdk.execution",
        "ExecutionRequirements",
    ),
    "ExecutionResource": ("qpane.sdk.execution", "ExecutionResource"),
    "ExecutionRuntime": ("qpane.sdk.execution", "ExecutionRuntime"),
    "ExecutionScope": ("qpane.sdk.execution", "ExecutionScope"),
    "ExecutionSnapshot": ("qpane.sdk.execution", "ExecutionSnapshot"),
    "ExecutionState": ("qpane.sdk.execution", "ExecutionState"),
    "ExecutionTagValue": ("qpane.sdk.execution", "ExecutionTagValue"),
    "ExecutionTaskContext": (
        "qpane.sdk.execution",
        "ExecutionTaskContext",
    ),
    "ExecutionTimings": ("qpane.sdk.execution", "ExecutionTimings"),
    "ExecutionUrgency": ("qpane.sdk.execution", "ExecutionUrgency"),
    "InlineDispatcher": ("qpane.sdk.execution", "InlineDispatcher"),
    "QtDelayScheduler": ("qpane.sdk.execution", "QtDelayScheduler"),
    "QtOwnerDispatcher": ("qpane.sdk.execution", "QtOwnerDispatcher"),
    "RetryCategorySnapshot": (
        "qpane.sdk.execution",
        "RetryCategorySnapshot",
    ),
    "RetryContext": ("qpane.sdk.execution", "RetryContext"),
    "RetryController": ("qpane.sdk.execution", "RetryController"),
    "RetryPolicy": ("qpane.sdk.execution", "RetryPolicy"),
    "RetrySchedulingError": (
        "qpane.sdk.execution",
        "RetrySchedulingError",
    ),
    "RetrySnapshot": ("qpane.sdk.execution", "RetrySnapshot"),
    "create_default_execution_runtime": (
        "qpane.sdk.execution",
        "create_default_execution_runtime",
    ),
    "create_native_execution_runtime": (
        "qpane.sdk.execution",
        "create_native_execution_runtime",
    ),
    "execution_detail_records": (
        "qpane.sdk.execution",
        "execution_detail_records",
    ),
    "execution_summary_records": (
        "qpane.sdk.execution",
        "execution_summary_records",
    ),
    "retry_detail_records": (
        "qpane.sdk.execution",
        "retry_detail_records",
    ),
    "retry_summary_records": (
        "qpane.sdk.execution",
        "retry_summary_records",
    ),
    "NavigationInteractionPort": (
        "qpane.interaction",
        "NavigationInteractionPort",
    ),
    "OutboundDragPayload": ("qpane.sdk.ui", "OutboundDragPayload"),
    "OutboundMimeItem": ("qpane.sdk.ui", "OutboundMimeItem"),
    "PanZoomTool": ("qpane.interaction", "PanZoomTool"),
    "ToolInputProfile": ("qpane.interaction", "ToolInputProfile"),
    "ToolManager": ("qpane.interaction", "ToolManager"),
    "ToolManagerSignals": ("qpane.interaction", "ToolManagerSignals"),
    "TouchGestureArena": ("qpane.interaction", "TouchGestureArena"),
    "TouchGestureKind": ("qpane.interaction", "TouchGestureKind"),
    "TouchNavigationPort": ("qpane.interaction", "TouchNavigationPort"),
    "TouchNavigationSession": ("qpane.interaction", "TouchNavigationSession"),
    "ViewerTool": ("qpane.interaction", "ViewerTool"),
    "ViewerToolSignals": ("qpane.interaction", "ViewerToolSignals"),
    "ViewerCatalog": ("qpane.catalog", "ViewerCatalog"),
    "ViewerCatalogEntry": ("qpane.catalog", "ViewerCatalogEntry"),
    "ViewerPlaceholderState": ("qpane.catalog", "ViewerPlaceholderState"),
    "ViewerPrefetchSnapshot": ("qpane.catalog", "ViewerPrefetchSnapshot"),
    "LinkedGroup": ("qpane.types", "LinkedGroup"),
    "InspectionRegion": ("qpane.inspection", "InspectionRegion"),
    "InspectionStateStore": ("qpane.inspection", "InspectionStateStore"),
    "InspectionTarget": ("qpane.inspection", "InspectionTarget"),
    "InspectionUpdate": ("qpane.inspection", "InspectionUpdate"),
    "InspectionViewState": ("qpane.inspection", "InspectionViewState"),
    "InspectionZoomMode": ("qpane.inspection", "InspectionZoomMode"),
    "ProjectedViewport": ("qpane.inspection", "ProjectedViewport"),
    "capture_inspection": ("qpane.inspection", "capture_inspection"),
    "project_inspection": ("qpane.inspection", "project_inspection"),
    "HybridCombineMode": ("qpane.hybrid", "HybridCombineMode"),
    "HybridDocument": ("qpane.hybrid", "HybridDocument"),
    "HybridPresentationStyle": ("qpane.hybrid", "HybridPresentationStyle"),
    "HybridRasterPrimitive": ("qpane.hybrid", "HybridRasterPrimitive"),
    "HybridRasterSampler": ("qpane.hybrid", "HybridRasterSampler"),
    "HybridVectorPrimitive": ("qpane.hybrid", "HybridVectorPrimitive"),
    "IncompleteRowAlignment": ("qpane.layout", "IncompleteRowAlignment"),
    "HybridSource": ("qpane.rendering.sdk", "HybridSource"),
    "RasterBounds": ("qpane.scene.raster", "RasterBounds"),
    "RasterProductPolicy": (
        "qpane.scene.source_capabilities",
        "RasterProductPolicy",
    ),
    "RasterSourcePatch": (
        "qpane.scene.source_capabilities",
        "RasterSourcePatch",
    ),
    "RasterHitTestProvider": ("qpane.rendering.sdk", "RasterHitTestProvider"),
    "RasterSource": ("qpane.rendering.sdk", "RasterSource"),
    "RasterSourceProvider": ("qpane.rendering.sdk", "RasterSourceProvider"),
    "ResponsiveGridLayout": ("qpane.layout", "ResponsiveGridLayout"),
    "ResponsiveGridPolicy": ("qpane.layout", "ResponsiveGridPolicy"),
    "ResponsiveGridSnapshot": ("qpane.layout", "ResponsiveGridSnapshot"),
    "ResponsiveGridTopology": ("qpane.layout", "ResponsiveGridTopology"),
    "RenderLayer": ("qpane.rendering.sdk", "RenderLayer"),
    "RenderScene": ("qpane.rendering.sdk", "RenderScene"),
    "SceneSnapshotOverlayLayer": (
        "qpane.types",
        "SceneSnapshotOverlayLayer",
    ),
    "SceneSnapshotOverlayState": (
        "qpane.types",
        "SceneSnapshotOverlayState",
    ),
    "SparseRasterSourceProvider": (
        "qpane.rendering.sdk",
        "SparseRasterSourceProvider",
    ),
    "VectorSource": ("qpane.rendering.sdk", "VectorSource"),
    "VectorDocument": ("qpane.vector", "VectorDocument"),
    "VectorObject": ("qpane.vector", "VectorObject"),
    "VectorFillRule": ("qpane.vector", "VectorFillRule"),
    "VectorObjectKind": ("qpane.vector", "VectorObjectKind"),
    "VectorParagraphStyle": ("qpane.vector", "VectorParagraphStyle"),
    "VectorPathCommand": ("qpane.vector", "VectorPathCommand"),
    "VectorPathCommandKind": ("qpane.vector", "VectorPathCommandKind"),
    "VectorShapeKind": ("qpane.vector", "VectorShapeKind"),
    "VectorStrokeCap": ("qpane.vector", "VectorStrokeCap"),
    "VectorStrokeJoin": ("qpane.vector", "VectorStrokeJoin"),
    "VectorStyle": ("qpane.vector", "VectorStyle"),
    "VectorTextAlignment": ("qpane.vector", "VectorTextAlignment"),
    "VectorTextContent": ("qpane.vector", "VectorTextContent"),
    "VectorTextDirection": ("qpane.vector", "VectorTextDirection"),
    "VectorTextSpan": ("qpane.vector", "VectorTextSpan"),
    "VectorTextStyle": ("qpane.vector", "VectorTextStyle"),
    "__version__": ("qpane._version", "version"),
}


def __getattr__(name: str) -> Any:
    """Load public values without importing the widget or Qt workers eagerly."""
    target = _LAZY_SYMBOLS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(target[0]), target[1])
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return the complete lazy public surface."""
    return sorted(__all__)
