#    Ferrastra - CPU-first native graphics product engine
#    Copyright (C) 2025  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import TypeAlias, final

_ReadableBuffer: TypeAlias = bytes | bytearray | memoryview

class FerrastraError(Exception): ...
class GraphError(FerrastraError): ...
class EvaluationError(FerrastraError): ...
class BufferError(FerrastraError): ...

@final
class Region:
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

@final
class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

@final
class EvaluationBudget:
    def __init__(
        self,
        *,
        memory_bytes: int,
        scratch_bytes: int = 0,
        threads: int = 1,
        cancellation: CancellationToken | None = None,
    ) -> None: ...
    @property
    def memory_bytes(self) -> int: ...
    @property
    def scratch_bytes(self) -> int: ...
    @property
    def threads(self) -> int: ...

@final
class EvaluationRequirements:
    @property
    def memory_bytes(self) -> int: ...
    @property
    def scratch_bytes(self) -> int: ...

@final
class Graph:
    @staticmethod
    def from_json(serialized: str) -> Graph: ...
    def to_json(self) -> str: ...
    @property
    def content_id(self) -> str: ...
    @property
    def revision_id(self) -> int: ...
    @property
    def schema_version(self) -> int: ...

@final
class GraphBuilder:
    def __init__(self, revision_id: int, *, schema_version: int = 1) -> None: ...
    def add_node(
        self, node_id: int, operation_id: str, *, semantic_version: int = 1
    ) -> None: ...
    def set_source_revision(self, node_id: int, revision: str) -> None: ...
    def connect(
        self,
        source_node: int,
        source_port: str,
        destination_node: int,
        destination_port: str,
    ) -> None: ...
    def add_output(
        self, name: str, node_id: int, *, port_name: str = "result"
    ) -> None: ...
    def set_boolean(self, node_id: int, parameter: str, value: bool) -> None: ...
    def set_integer(self, node_id: int, parameter: str, value: int) -> None: ...
    def set_scalar(self, node_id: int, parameter: str, value: float) -> None: ...
    def set_text(self, node_id: int, parameter: str, value: str) -> None: ...
    def set_enum(self, node_id: int, parameter: str, value: str) -> None: ...
    def set_label(self, label: str | None) -> None: ...
    def build(self) -> Graph: ...

@final
class CompiledGraph:
    @property
    def graph_content_id(self) -> str: ...

@final
class RasterResult:
    @property
    def pixels(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride_bytes(self) -> int: ...
    @property
    def format(self) -> str: ...
    @property
    def product_id(self) -> str: ...
    @property
    def graph_content_id(self) -> str: ...
    @property
    def peak_memory_bytes(self) -> int: ...
    @property
    def evaluated_nodes(self) -> int: ...
    @property
    def produced_samples(self) -> int: ...

@final
class CoverageResult:
    @property
    def pixels(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride_bytes(self) -> int: ...
    @property
    def format(self) -> str: ...
    @property
    def product_id(self) -> str: ...
    @property
    def graph_content_id(self) -> str: ...
    @property
    def peak_memory_bytes(self) -> int: ...
    @property
    def evaluated_nodes(self) -> int: ...
    @property
    def produced_samples(self) -> int: ...

@final
class Engine:
    def __init__(self) -> None: ...
    def add_rgba8(
        self,
        data: _ReadableBuffer,
        width: int,
        height: int,
        *,
        stride_bytes: int | None = None,
    ) -> str: ...
    def add_coverage8(
        self,
        data: _ReadableBuffer,
        width: int,
        height: int,
        *,
        stride_bytes: int | None = None,
    ) -> str: ...
    def compile(self, graph: Graph) -> CompiledGraph: ...
    def requirements(
        self,
        compiled: CompiledGraph,
        output_name: str,
        region: Region,
    ) -> EvaluationRequirements: ...
    def evaluate(
        self,
        compiled: CompiledGraph,
        output_name: str,
        region: Region,
        budget: EvaluationBudget,
    ) -> RasterResult | CoverageResult: ...

def package_version() -> str: ...
